name: test

on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command

    - name: lint
      uses: borales/actions-yarn@v4
      with:
        cmd: lint # will run `yarn lint` command

    - name: tscheck
      uses: borales/actions-yarn@v4
      with:
        cmd: tscheck # will run `yarn tscheck` command

    - name: test
      uses: borales/actions-yarn@v4
      with:
        cmd: test # will run `yarn test` command
